### ISSUE TITLE
How could I deploy InfluxDB OSS service 

### ISSUE THREAD

**Issue by luopuya** [influxdata/terraform-influxdb#1]
I'm not sure how to use this module to deploy InfluxDB OSS service.

What should I do?
Terraform apply (with 1 data node and 0 meta node), and then install InfluxDB package on instance ?

Thx

**Comment by xe-nvdk** [comment]
Hey, thank you for open an issue. This module is only for enterprise version. if you're interested I can build something similar to OSS. 1.x and 2.x.
